// Comprehensive Nigerian meals database with improved recipes
export const fallbackMeals = [
  // BREAKFAST OPTIONS (15 recipes)
  {
    id: 1,
    name: "Akara and Bread",
    description: "Crispy bean fritters served with fresh bread - a Nigerian classic that never gets old",
    meal_type: "breakfast",
    dietary_preference: "any",
    cooking_time: "quick",
    prep_time: "20 mins",
    difficulty: "easy",
    ingredients: [
      "Black-eyed peas (1 cup, soaked overnight)",
      "Onions (1 medium, roughly chopped)",
      "Scotch bonnet pepper (1-2 pieces, to taste)",
      "Salt (1/2 teaspoon)",
      "Fresh bread (4 slices)",
      "Palm oil (1/2 cup for frying)",
      "Water (1/4 cup for blending)"
    ],
    instructions: [
      "Soak black-eyed peas overnight, then peel off the skins by rubbing between your hands",
      "Rinse peeled beans and drain well",
      "Blend beans with onions, pepper, and water until smooth (not too watery)",
      "Add salt and mix well with a wooden spoon",
      "Heat palm oil in a deep pan until hot (test with a drop of batter)",
      "Drop spoonfuls of batter into hot oil and fry until golden brown on both sides",
      "Remove and drain on paper towels",
      "Serve hot with fresh bread and optional pepper sauce"
    ],
    cuisine_type: "Nigerian"
  },
  {
    id: 2,
    name: "Moi Moi",
    description: "Steamed bean pudding packed with flavor - perfect for a filling breakfast",
    meal_type: "breakfast",
    dietary_preference: "vegetarian",
    cooking_time: "regular",
    prep_time: "45 mins",
    difficulty: "medium",
    ingredients: [
      "Black-eyed peas (2 cups, soaked overnight)",
      "Red bell peppers (2 medium, roughly chopped)",
      "Onions (1 large, roughly chopped)",
      "Palm oil (1/3 cup)",
      "Seasoning cubes (2 pieces, crushed)",
      "Boiled eggs (4 pieces, peeled and halved)",
      "Carrots (1 medium, diced)",
      "Salt (1 teaspoon)",
      "Water (1/2 cup for blending)"
    ],
    instructions: [
      "Soak black-eyed peas overnight, then peel off the skins",
      "Blend peeled beans with peppers, onions, and water until very smooth",
      "Transfer to a large bowl and add palm oil, crushed seasoning cubes, and salt",
      "Mix thoroughly with a wooden spoon until well combined",
      "Prepare containers (aluminum foil, banana leaves, or ramekins)",
      "Pour mixture into containers, add egg and carrot pieces",
      "Cover containers tightly with foil",
      "Steam in a large pot for 35-40 minutes until firm and cooked through",
      "Let cool for 5 minutes before serving"
    ],
    cuisine_type: "Nigerian"
  },
  {
    id: 3,
    name: "Yam and Egg Sauce",
    description: "Boiled yam with scrambled eggs in tomato sauce - simple yet satisfying",
    meal_type: "breakfast",
    dietary_preference: "any",
    cooking_time: "quick",
    prep_time: "25 mins",
    difficulty: "easy",
    ingredients: [
      "White yam (1 medium tuber, peeled and cut into chunks)",
      "Eggs (4 pieces)",
      "Tomatoes (3 medium, roughly chopped)",
      "Onions (1 medium, diced)",
      "Scotch bonnet pepper (1 piece, chopped)",
      "Vegetable oil (3 tablespoons)",
      "Salt (1/2 teaspoon)",
      "Seasoning cube (1 piece, crushed)",
      "Water (for boiling yam)"
    ],
    instructions: [
      "Peel and cut yam into medium chunks, rinse well",
      "Boil yam in salted water until tender (about 15-20 minutes)",
      "While yam cooks, blend tomatoes with onions and pepper until smooth",
      "Heat oil in a pan and fry tomato mixture until thick and oily (about 8-10 minutes)",
      "Add crushed seasoning cube and salt, stir well",
      "Crack eggs into the sauce and scramble gently until just set",
      "Drain yam and serve hot with the egg sauce",
      "Optional: serve with fried plantains or bread"
    ],
    cuisine_type: "Nigerian"
  },
  {
    id: 4,
    name: "Bread and Tea",
    description: "Nigerian-style milk tea with fresh bread - perfect for busy mornings",
    meal_type: "breakfast",
    dietary_preference: "vegetarian",
    cooking_time: "quick",
    prep_time: "10 mins",
    difficulty: "easy",
    ingredients: [
      "Fresh bread (4-6 slices)",
      "Tea bags (2 Lipton or similar)",
      "Peak milk (1/2 cup)",
      "Sugar (2-3 tablespoons, to taste)",
      "Ginger (1/2 inch, peeled and sliced)",
      "Cloves (3-4 pieces)",
      "Water (2 cups)",
      "Butter (for bread, optional)"
    ],
    instructions: [
      "Bring water to boil in a kettle or pot",
      "Add ginger slices and cloves to boiling water",
      "Add tea bags and steep for 3-4 minutes",
      "Remove tea bags and add milk",
      "Add sugar to taste and stir well",
      "Let it simmer for 1 minute",
      "Strain into cups to remove ginger and cloves",
      "Serve hot with buttered bread or toast"
    ],
    cuisine_type: "Nigerian"
  },
  {
    id: 5,
    name: "Plantain Pancakes",
    description: "Sweet plantain pancakes with a Nigerian twist - kids love these!",
    meal_type: "breakfast",
    dietary_preference: "vegetarian",
    cooking_time: "quick",
    prep_time: "20 mins",
    difficulty: "easy",
    ingredients: [
      "Ripe plantain (2 medium pieces, peeled and mashed)",
      "Flour (1 cup)",
      "Eggs (2 pieces)",
      "Milk (1/2 cup)",
      "Sugar (2 tablespoons)",
      "Nutmeg (1/4 teaspoon)",
      "Baking powder (1 teaspoon)",
      "Salt (1/4 teaspoon)",
      "Vegetable oil (for frying)",
      "Honey or syrup (for serving)"
    ],
    instructions: [
      "Mash ripe plantains until smooth in a large bowl",
      "Add eggs and milk, whisk until well combined",
      "In a separate bowl, mix flour, sugar, nutmeg, baking powder, and salt",
      "Gradually add dry ingredients to wet mixture, stirring gently",
      "Heat a non-stick pan over medium heat with a little oil",
      "Pour 1/4 cup batter for each pancake",
      "Cook until bubbles form on top (about 2-3 minutes)",
      "Flip and cook other side until golden (about 1-2 minutes)",
      "Serve hot with honey, syrup, or fresh fruit"
    ],
    cuisine_type: "Nigerian"
  },
  {
    id: 6,
    name: "Jollof Rice",
    description: "The crown jewel of Nigerian cuisine - perfectly spiced rice that everyone loves",
    meal_type: "lunch",
    dietary_preference: "any",
    cooking_time: "regular",
    prep_time: "50 mins",
    difficulty: "medium",
    ingredients: [
      "Basmati rice (3 cups, washed and drained)",
      "Tomatoes (5 large, roughly chopped)",
      "Red bell peppers (2 medium, roughly chopped)",
      "Onions (1 large, roughly chopped)",
      "Scotch bonnet pepper (1-2 pieces, to taste)",
      "Chicken stock (4 cups)",
      "Bay leaves (2 pieces)",
      "Thyme (1 teaspoon)",
      "Curry powder (2 tablespoons)",
      "Palm oil (1/2 cup)",
      "Seasoning cubes (2 pieces, crushed)",
      "Salt (1 teaspoon)",
      "Garlic (3 cloves, minced)",
      "Ginger (1 inch, minced)"
    ],
    instructions: [
      "Blend tomatoes, peppers, onions, and scotch bonnet until smooth",
      "Heat palm oil in a large pot until hot",
      "Add minced garlic and ginger, fry for 1 minute",
      "Pour in blended mixture and fry until thick and oily (about 15-20 minutes)",
      "Add crushed seasoning cubes, salt, thyme, curry powder, and bay leaves",
      "Stir well and add chicken stock",
      "Bring to boil and add washed rice",
      "Reduce heat to low, cover and cook for 20-25 minutes",
      "Check rice is tender, then let it steam for 10 minutes",
      "Fluff with fork and serve hot with grilled chicken or fish"
    ],
    cuisine_type: "Nigerian"
  },
  {
    id: 7,
    name: "Egusi Soup with Pounded Yam",
    description: "Rich melon seed soup with assorted meat - a true comfort meal",
    meal_type: "lunch",
    dietary_preference: "any",
    cooking_time: "elaborate",
    prep_time: "75 mins",
    difficulty: "medium",
    ingredients: [
      "Ground egusi (2 cups)",
      "Spinach (2 bunches, washed and chopped)",
      "Assorted meat (1kg - beef, goat, tripe)",
      "Stockfish (200g, soaked and cleaned)",
      "Palm oil (1 cup)",
      "Onions (2 medium, diced)",
      "Scotch bonnet pepper (2 pieces, chopped)",
      "Seasoning cubes (3 pieces, crushed)",
      "Salt (1 teaspoon)",
      "Crayfish (2 tablespoons, ground)",
      "Pounded yam (for serving)",
      "Water (6 cups)"
    ],
    instructions: [
      "Season and cook assorted meat with onions, salt, and seasoning cubes until tender (about 45 minutes)",
      "Add soaked stockfish and cook for additional 15 minutes",
      "Remove meat and stockfish, reserve stock",
      "Heat palm oil in a large pot until hot",
      "Add ground egusi and fry, stirring constantly until golden (about 10 minutes)",
      "Gradually add meat stock while stirring to avoid lumps",
      "Add cooked meat and stockfish",
      "Add crayfish and simmer for 10 minutes",
      "Add chopped spinach and simmer for 5 minutes",
      "Adjust seasoning and serve hot with pounded yam"
    ],
    cuisine_type: "Nigerian"
  },
  {
    id: 8,
    name: "Fried Rice Nigerian Style",
    description: "Colorful rice with mixed vegetables - perfect for special occasions",
    meal_type: "lunch",
    dietary_preference: "any",
    cooking_time: "quick",
    prep_time: "35 mins",
    difficulty: "easy",
    ingredients: [
      "Rice (3 cups, parboiled and drained)",
      "Carrots (2 medium, diced)",
      "Green beans (1 cup, chopped)",
      "Sweet corn (1/2 cup)",
      "Green peas (1/2 cup)",
      "Chicken (500g, diced)",
      "Curry powder (2 tablespoons)",
      "Thyme (1 teaspoon)",
      "Onions (1 medium, diced)",
      "Vegetable oil (1/3 cup)",
      "Seasoning cubes (2 pieces, crushed)",
      "Salt (1 teaspoon)",
      "Garlic (2 cloves, minced)"
    ],
    instructions: [
      "Parboil rice for 5 minutes, drain and set aside",
      "Season chicken with salt, curry powder, and crushed seasoning cubes",
      "Heat oil in a large wok or pan",
      "Fry chicken until golden brown, remove and set aside",
      "In same oil, sauté onions and garlic until fragrant",
      "Add diced vegetables and stir-fry for 3-4 minutes",
      "Add curry powder and thyme, stir well",
      "Add parboiled rice and mix gently",
      "Add fried chicken and stir-fry for 5-7 minutes",
      "Season with salt and serve hot"
    ],
    cuisine_type: "Nigerian"
  },
  {
    id: 9,
    name: "Pepper Soup",
    description: "Spicy, aromatic soup perfect for dinner - warms the soul",
    meal_type: "dinner",
    dietary_preference: "any",
    cooking_time: "regular",
    prep_time: "50 mins",
    difficulty: "easy",
    ingredients: [
      "Goat meat (1kg, cut into pieces)",
      "Pepper soup spice (2 tablespoons)",
      "Onions (1 large, sliced)",
      "Ginger (1 inch, sliced)",
      "Garlic (4 cloves, minced)",
      "Scent leaves (1 bunch, washed)",
      "Yam (1 medium, peeled and cubed)",
      "Scotch bonnet pepper (2 pieces, whole)",
      "Seasoning cubes (2 pieces, crushed)",
      "Salt (1 teaspoon)",
      "Water (6 cups)"
    ],
    instructions: [
      "Clean and cut goat meat into medium pieces",
      "Season meat with salt, crushed seasoning cubes, and pepper soup spice",
      "Place meat in a large pot with water and bring to boil",
      "Reduce heat and simmer until meat is tender (about 30-40 minutes)",
      "Add yam cubes and cook until soft (about 15 minutes)",
      "Add sliced onions, ginger, garlic, and whole scotch bonnet",
      "Simmer for additional 10 minutes",
      "Add scent leaves in the last 2 minutes",
      "Adjust seasoning and serve hot"
    ],
    cuisine_type: "Nigerian"
  },
  {
    id: 10,
    name: "Rice and Stew",
    description: "Classic white rice with rich tomato stew - a household favorite",
    meal_type: "dinner",
    dietary_preference: "any",
    cooking_time: "regular",
    prep_time: "60 mins",
    difficulty: "easy",
    ingredients: [
      "Rice (3 cups, washed and drained)",
      "Tomatoes (6 large, roughly chopped)",
      "Beef (500g, cut into pieces)",
      "Onions (2 medium, roughly chopped)",
      "Red peppers (2 medium, roughly chopped)",
      "Palm oil (1/2 cup)",
      "Seasoning cubes (2 pieces, crushed)",
      "Salt (1 teaspoon)",
      "Garlic (3 cloves, minced)",
      "Ginger (1 inch, minced)",
      "Water (for cooking rice and stew)"
    ],
    instructions: [
      "Cook rice in salted water until fluffy, drain and set aside",
      "Season beef with salt and crushed seasoning cubes",
      "Blend tomatoes, peppers, and onions until smooth",
      "Heat palm oil in a large pot until hot",
      "Add minced garlic and ginger, fry for 1 minute",
      "Add seasoned beef and fry until brown on all sides",
      "Pour in blended tomato mixture and fry until thick and oily (about 20 minutes)",
      "Add water if needed and simmer until meat is tender",
      "Adjust seasoning and serve hot rice with stew"
    ],
    cuisine_type: "Nigerian"
  },
  {
    id: 11,
    name: "Indomie and Egg",
    description: "Quick noodles with fried egg - for those really busy days",
    meal_type: "lunch",
    dietary_preference: "any",
    cooking_time: "quick",
    prep_time: "10 mins",
    difficulty: "easy",
    ingredients: [
      "Indomie noodles (2 packs)",
      "Eggs (2 pieces)",
      "Onions (1 small, diced)",
      "Tomatoes (1 medium, diced)",
      "Vegetable oil (2 tablespoons)",
      "Seasoning (from noodle packs)",
      "Salt (to taste)",
      "Water (4 cups for boiling)"
    ],
    instructions: [
      "Bring water to boil in a pot",
      "Add noodles and cook for 3 minutes",
      "Drain noodles and set aside",
      "Heat oil in a pan and fry diced onions until translucent",
      "Add diced tomatoes and fry for 2 minutes",
      "Push vegetables to one side and fry eggs in the same pan",
      "Add cooked noodles and seasoning packets",
      "Mix well and cook for 2 minutes",
      "Serve hot with fried egg on top"
    ],
    cuisine_type: "Nigerian"
  },
  {
    id: 12,
    name: "Plantain and Beans",
    description: "Sweet plantain with beans porridge - filling and nutritious",
    meal_type: "dinner",
    dietary_preference: "vegetarian",
    cooking_time: "regular",
    prep_time: "45 mins",
    difficulty: "easy",
    ingredients: [
      "Ripe plantain (2 medium, peeled and cut into chunks)",
      "Brown beans (2 cups, soaked overnight)",
      "Palm oil (1/3 cup)",
      "Onions (1 medium, diced)",
      "Scotch bonnet pepper (1 piece, chopped)",
      "Crayfish (2 tablespoons, ground)",
      "Seasoning cubes (2 pieces, crushed)",
      "Salt (1 teaspoon)",
      "Water (6 cups)"
    ],
    instructions: [
      "Soak beans overnight, then rinse and drain",
      "Cook beans in water until almost soft (about 30 minutes)",
      "Add plantain chunks and cook for 10 minutes",
      "Add palm oil, diced onions, and pepper",
      "Add crayfish, crushed seasoning cubes, and salt",
      "Simmer until plantain is tender and beans are soft",
      "Stir gently to avoid breaking plantain",
      "Serve hot with optional fried fish or meat"
    ],
    cuisine_type: "Nigerian"
  },
  {
    id: 13,
    name: "Amala and Ewedu",
    description: "Yam flour with jute leaf soup - a Yoruba classic",
    meal_type: "lunch",
    dietary_preference: "any",
    cooking_time: "regular",
    prep_time: "40 mins",
    difficulty: "medium",
    ingredients: [
      "Yam flour (2 cups)",
      "Ewedu leaves (1 bunch, washed)",
      "Locust beans (2 tablespoons)",
      "Palm oil (1/4 cup)",
      "Assorted meat (500g, cooked)",
      "Scotch bonnet pepper (1 piece)",
      "Seasoning cubes (2 pieces, crushed)",
      "Salt (1 teaspoon)",
      "Water (for cooking)"
    ],
    instructions: [
      "Cook assorted meat with seasoning until tender, reserve stock",
      "Blend ewedu leaves with a little water until smooth",
      "Pour blended ewedu into a pot with meat stock",
      "Add locust beans, palm oil, and crushed seasoning cubes",
      "Cook on medium heat, stirring occasionally until thick (about 15 minutes)",
      "For amala: bring water to boil in a separate pot",
      "Gradually add yam flour while stirring vigorously to avoid lumps",
      "Continue stirring until smooth and stretchy",
      "Serve hot amala with ewedu soup and meat"
    ],
    cuisine_type: "Nigerian"
  },
  {
    id: 14,
    name: "Okra Soup",
    description: "Nutritious okra soup with assorted meat - sticky and delicious",
    meal_type: "dinner",
    dietary_preference: "any",
    cooking_time: "regular",
    prep_time: "45 mins",
    difficulty: "easy",
    ingredients: [
      "Fresh okra (500g, sliced into rings)",
      "Assorted meat (500g, cut into pieces)",
      "Fish (200g, cleaned and cut)",
      "Palm oil (1/2 cup)",
      "Onions (1 medium, diced)",
      "Scotch bonnet pepper (2 pieces, chopped)",
      "Seasoning cubes (2 pieces, crushed)",
      "Crayfish (2 tablespoons, ground)",
      "Salt (1 teaspoon)",
      "Water (4 cups)"
    ],
    instructions: [
      "Season and cook assorted meat until tender, reserve stock",
      "Add fish to meat stock and cook for 10 minutes",
      "Remove fish and meat, set aside",
      "Heat palm oil in a pot and sauté onions until translucent",
      "Add sliced okra and stir-fry for 3-4 minutes",
      "Add meat stock gradually while stirring",
      "Add crayfish, crushed seasoning cubes, and salt",
      "Add cooked meat and fish",
      "Simmer until okra is tender and soup is thick",
      "Serve hot with your choice of swallow (eba, amala, etc.)"
    ],
    cuisine_type: "Nigerian"
  },
  {
    id: 15,
    name: "Spaghetti Jollof",
    description: "Spaghetti cooked jollof style - a fusion favorite",
    meal_type: "dinner",
    dietary_preference: "any",
    cooking_time: "quick",
    prep_time: "30 mins",
    difficulty: "easy",
    ingredients: [
      "Spaghetti (400g)",
      "Tomatoes (4 large, roughly chopped)",
      "Onions (1 medium, roughly chopped)",
      "Red bell peppers (2 medium, roughly chopped)",
      "Curry powder (2 tablespoons)",
      "Thyme (1 teaspoon)",
      "Chicken stock (4 cups)",
      "Palm oil (1/3 cup)",
      "Seasoning cubes (2 pieces, crushed)",
      "Salt (1 teaspoon)",
      "Garlic (2 cloves, minced)"
    ],
    instructions: [
      "Blend tomatoes, peppers, and onions until smooth",
      "Heat palm oil in a large pot until hot",
      "Add minced garlic and fry for 1 minute",
      "Pour in blended mixture and fry until thick and oily (about 15 minutes)",
      "Add curry powder, thyme, crushed seasoning cubes, and salt",
      "Add chicken stock and bring to boil",
      "Add spaghetti and cook according to package instructions",
      "Stir occasionally to prevent sticking",
      "Cook until pasta is tender and sauce is thick",
      "Serve hot with grilled chicken or fish"
    ],
    cuisine_type: "Nigerian"
  },
  {
    id: 16,
    name: "Vegetable Soup",
    description: "Mixed vegetable soup with assorted meat - healthy and tasty",
    meal_type: "dinner",
    dietary_preference: "any",
    cooking_time: "regular",
    prep_time: "40 mins",
    difficulty: "easy",
    ingredients: [
      "Spinach (2 bunches, washed and chopped)",
      "Waterleaf (1 bunch, washed and chopped)",
      "Assorted meat (500g, cut into pieces)",
      "Palm oil (1/2 cup)",
      "Crayfish (3 tablespoons, ground)",
      "Seasoning cubes (2 pieces, crushed)",
      "Onions (1 medium, diced)",
      "Scotch bonnet pepper (1 piece, chopped)",
      "Salt (1 teaspoon)",
      "Water (4 cups)"
    ],
    instructions: [
      "Season and cook assorted meat until tender, reserve stock",
      "Heat palm oil in a pot and sauté onions until translucent",
      "Add chopped pepper and fry for 1 minute",
      "Add meat stock and bring to boil",
      "Add chopped vegetables (waterleaf first, then spinach)",
      "Add crayfish, crushed seasoning cubes, and salt",
      "Simmer for 5-7 minutes until vegetables are tender",
      "Add cooked meat and simmer for 2 minutes",
      "Serve hot with your choice of swallow"
    ],
    cuisine_type: "Nigerian"
  },
  {
    id: 17,
    name: "Beans and Plantain Porridge",
    description: "One-pot meal with beans and plantain - very filling",
    meal_type: "lunch",
    dietary_preference: "vegetarian",
    cooking_time: "elaborate",
    prep_time: "65 mins",
    difficulty: "easy",
    ingredients: [
      "Brown beans (2 cups, soaked overnight)",
      "Ripe plantain (2 medium, peeled and cut into chunks)",
      "Palm oil (1/2 cup)",
      "Onions (1 medium, diced)",
      "Scotch bonnet pepper (1 piece, chopped)",
      "Spinach (1 bunch, washed and chopped)",
      "Crayfish (2 tablespoons, ground)",
      "Seasoning cubes (2 pieces, crushed)",
      "Salt (1 teaspoon)",
      "Water (6 cups)"
    ],
    instructions: [
      "Soak beans overnight, then rinse and drain",
      "Cook beans in water until almost soft (about 40 minutes)",
      "Add plantain chunks and cook for 10 minutes",
      "Add palm oil, diced onions, and chopped pepper",
      "Add crayfish, crushed seasoning cubes, and salt",
      "Simmer until plantain is tender and beans are soft",
      "Add chopped spinach in the last 5 minutes",
      "Stir gently to avoid breaking plantain",
      "Serve hot with optional fried fish or meat"
    ],
    cuisine_type: "Nigerian"
  },
  {
    id: 18,
    name: "Catfish Pepper Soup",
    description: "Spicy catfish soup - perfect for cold evenings",
    meal_type: "dinner",
    dietary_preference: "any",
    cooking_time: "quick",
    prep_time: "35 mins",
    difficulty: "easy",
    ingredients: [
      "Fresh catfish (1kg, cleaned and cut into pieces)",
      "Pepper soup spice (2 tablespoons)",
      "Ginger (1 inch, sliced)",
      "Garlic (4 cloves, minced)",
      "Scent leaves (1 bunch, washed)",
      "Yam (1 medium, peeled and cubed)",
      "Onions (1 medium, sliced)",
      "Scotch bonnet pepper (2 pieces, whole)",
      "Seasoning cubes (2 pieces, crushed)",
      "Salt (1 teaspoon)",
      "Water (4 cups)"
    ],
    instructions: [
      "Clean and cut catfish into medium pieces",
      "Season fish with salt, crushed seasoning cubes, and pepper soup spice",
      "Place fish in a large pot with water and bring to boil",
      "Add yam cubes and cook until soft (about 15 minutes)",
      "Add sliced onions, ginger, garlic, and whole scotch bonnet",
      "Simmer for additional 10 minutes",
      "Add scent leaves in the last 2 minutes",
      "Adjust seasoning and serve hot"
    ],
    cuisine_type: "Nigerian"
  },
  {
    id: 19,
    name: "White Rice and Chicken Stew",
    description: "Plain rice with rich chicken stew - always a winner",
    meal_type: "lunch",
    dietary_preference: "any",
    cooking_time: "regular",
    prep_time: "55 mins",
    difficulty: "easy",
    ingredients: [
      "Rice (3 cups, washed and drained)",
      "Chicken (1kg, cut into pieces)",
      "Tomatoes (5 large, roughly chopped)",
      "Onions (2 medium, roughly chopped)",
      "Red peppers (2 medium, roughly chopped)",
      "Palm oil (1/2 cup)",
      "Seasoning cubes (2 pieces, crushed)",
      "Salt (1 teaspoon)",
      "Garlic (3 cloves, minced)",
      "Ginger (1 inch, minced)",
      "Water (for cooking rice and stew)"
    ],
    instructions: [
      "Cook rice in salted water until fluffy, drain and set aside",
      "Season chicken with salt and crushed seasoning cubes",
      "Blend tomatoes, peppers, and onions until smooth",
      "Heat palm oil in a large pot until hot",
      "Add minced garlic and ginger, fry for 1 minute",
      "Add seasoned chicken and fry until brown on all sides",
      "Pour in blended tomato mixture and fry until thick and oily (about 20 minutes)",
      "Add water if needed and simmer until chicken is tender",
      "Adjust seasoning and serve hot rice with chicken stew"
    ],
    cuisine_type: "Nigerian"
  },
  {
    id: 20,
    name: "Yam Porridge (Asaro)",
    description: "Yam cooked in tomato sauce - comfort food at its best",
    meal_type: "lunch",
    dietary_preference: "any",
    cooking_time: "regular",
    prep_time: "40 mins",
    difficulty: "easy",
    ingredients: [
      "White yam (1 large tuber, peeled and cut into cubes)",
      "Tomatoes (4 large, roughly chopped)",
      "Onions (1 medium, roughly chopped)",
      "Palm oil (1/3 cup)",
      "Fish (200g, cleaned and cut)",
      "Spinach (1 bunch, washed and chopped)",
      "Scotch bonnet pepper (1 piece, chopped)",
      "Seasoning cubes (2 pieces, crushed)",
      "Salt (1 teaspoon)",
      "Water (3 cups)"
    ],
    instructions: [
      "Peel and cut yam into medium cubes, rinse well",
      "Blend tomatoes, onions, and pepper until smooth",
      "Heat palm oil in a large pot until hot",
      "Pour in blended mixture and fry until thick (about 10 minutes)",
      "Add yam cubes and stir to coat with sauce",
      "Add water, crushed seasoning cubes, and salt",
      "Add fish and simmer until yam is tender (about 20 minutes)",
      "Add chopped spinach in the last 5 minutes",
      "Stir gently and serve hot"
    ],
    cuisine_type: "Nigerian"
  },
  {
    id: 21,
    name: "Halal Chicken Suya",
    description: "Spicy grilled chicken skewers with traditional Nigerian spices - perfect for halal diets",
    meal_type: "dinner",
    dietary_preference: "halal",
    cooking_time: "regular",
    prep_time: "45 mins",
    difficulty: "medium",
    ingredients: [
      "Chicken breast (500g, cut into cubes)",
      "Groundnut powder (1/2 cup)",
      "Cayenne pepper (2 tablespoons)",
      "Paprika (1 tablespoon)",
      "Garlic powder (1 teaspoon)",
      "Ginger powder (1 teaspoon)",
      "Onion powder (1 teaspoon)",
      "Vegetable oil (3 tablespoons)",
      "Salt (1 teaspoon)",
      "Skewers (for grilling)"
    ],
    instructions: [
      "Cut chicken breast into 1-inch cubes",
      "Mix groundnut powder, cayenne pepper, paprika, garlic powder, ginger powder, onion powder, and salt",
      "Coat chicken cubes with the spice mixture",
      "Thread chicken onto skewers",
      "Heat vegetable oil in a grill pan or outdoor grill",
      "Grill chicken skewers for 8-10 minutes on each side until cooked through",
      "Serve hot with sliced onions and tomatoes"
    ],
    cuisine_type: "Nigerian"
  },
  {
    id: 22,
    name: "Pescatarian Fish Pepper Soup",
    description: "Spicy fish soup with traditional Nigerian herbs - perfect for pescatarian diets",
    meal_type: "dinner",
    dietary_preference: "pescatarian",
    cooking_time: "quick",
    prep_time: "30 mins",
    difficulty: "easy",
    ingredients: [
      "Fresh fish (500g, cleaned and cut)",
      "Scotch bonnet pepper (2 pieces)",
      "Onions (1 medium, sliced)",
      "Garlic (3 cloves, minced)",
      "Ginger (1 inch, minced)",
      "Utazi leaves (2 pieces)",
      "Uziza leaves (2 pieces)",
      "Vegetable oil (2 tablespoons)",
      "Salt (1 teaspoon)",
      "Water (4 cups)"
    ],
    instructions: [
      "Clean and cut fish into pieces",
      "Heat vegetable oil in a pot",
      "Add sliced onions, minced garlic, and ginger, fry for 2 minutes",
      "Add fish pieces and fry for 3 minutes",
      "Add water, salt, and scotch bonnet pepper",
      "Add utazi and uziza leaves",
      "Simmer for 15-20 minutes until fish is cooked",
      "Serve hot with boiled yam or rice"
    ],
    cuisine_type: "Nigerian"
  },
  {
    id: 23,
    name: "Gluten-Free Yam and Vegetable Stew",
    description: "Delicious yam stew with fresh vegetables - perfect for gluten-free diets",
    meal_type: "lunch",
    dietary_preference: "gluten_free",
    cooking_time: "regular",
    prep_time: "40 mins",
    difficulty: "easy",
    ingredients: [
      "White yam (1 large tuber, peeled and cut)",
      "Tomatoes (4 large, chopped)",
      "Bell peppers (2 medium, chopped)",
      "Onions (1 medium, chopped)",
      "Spinach (1 bunch, chopped)",
      "Vegetable oil (1/3 cup)",
      "Garlic (3 cloves, minced)",
      "Ginger (1 inch, minced)",
      "Salt (1 teaspoon)",
      "Water (3 cups)"
    ],
    instructions: [
      "Peel and cut yam into cubes, rinse well",
      "Heat vegetable oil in a large pot",
      "Add chopped onions, garlic, and ginger, fry for 2 minutes",
      "Add chopped tomatoes and bell peppers, fry for 5 minutes",
      "Add yam cubes and stir to coat with sauce",
      "Add water and salt, simmer for 20 minutes",
      "Add chopped spinach in the last 5 minutes",
      "Serve hot"
    ],
    cuisine_type: "Nigerian"
  }
];

// Common Nigerian ingredients for ingredient-based suggestions
export const commonIngredients = [
  "Rice", "Plantain", "Yam", "Tomatoes", "Onions", "Pepper",
  "Beans", "Chicken", "Beef", "Fish", "Eggs", "Spinach",
  "Palm oil", "Vegetable oil", "Garlic", "Ginger", "Okra",
  "Sweet potato", "Carrots", "Green beans", "Bread"
];

// Meal type options
export const mealTypes = [
  { value: "breakfast", label: "Breakfast", emoji: "🌅" },
  { value: "lunch", label: "Lunch", emoji: "☀️" },
  { value: "dinner", label: "Dinner", emoji: "🌙" }
];

// Cooking time options
export const cookingTimes = [
  { value: "quick", label: "Quick (Under 30 mins)", emoji: "⚡" },
  { value: "regular", label: "Regular (30-60 mins)", emoji: "⏰" },
  { value: "elaborate", label: "Elaborate (60+ mins)", emoji: "🕐" }
];

// Dietary preferences
export const dietaryPreferences = [
  { value: "any", label: "Any", emoji: "🍽️" },
  { value: "vegetarian", label: "Vegetarian", emoji: "🥬" },
  { value: "vegan", label: "Vegan", emoji: "🌱" },
  { value: "halal", label: "Halal", emoji: "☪️" },
  { value: "pescatarian", label: "Pescatarian", emoji: "🐟" },
  { value: "lacto_vegetarian", label: "Lacto-Vegetarian", emoji: "🥛" },
  { value: "gluten_free", label: "Gluten-Free", emoji: "🌾" },
  { value: "low_sodium", label: "Low-Sodium", emoji: "🧂" },
  { value: "diabetic_friendly", label: "Diabetic-Friendly", emoji: "🩺" },
  { value: "low_fat", label: "Low-Fat", emoji: "💪" }
];
